// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function PrepAllRules(){
	var bla = ds_list_create();
	
	ds_list_add(bla, "A is 1983");
	ds_list_add(bla, "Virgil is A");
	ds_list_add(bla, "B is 1984");
	ds_list_add(bla, "B is Horace");
	ds_list_add(bla, "C is 1985");
	ds_list_add(bla, "Eduardo is C");
	ds_list_add(bla, "D is 1986");
	ds_list_add(bla, "D is Bruce");
	ds_list_add(bla, "1987 is E");
	ds_list_add(bla, "Alfred is E");
	ds_list_add(bla, "Virgil is 1983");
	ds_list_add(bla, "Horace is 1984");
	ds_list_add(bla, "Eduardo is 1985");
	ds_list_add(bla, "1986 is Bruce");
	ds_list_add(bla, "Alfred is 1987");
	ds_list_add(bla, "A is not 1984");
	ds_list_add(bla, "1985 is not A");
	ds_list_add(bla, "A is not 1986");
	ds_list_add(bla, "A is not 1987");
	ds_list_add(bla, "A is not Alfred");
	ds_list_add(bla, "Bruce is not A");
	ds_list_add(bla, "A is not Eduardo");
	ds_list_add(bla, "A is not Horace");
	ds_list_add(bla, "1983 is not B");
	ds_list_add(bla, "1985 is not B");
	ds_list_add(bla, "1986 is not B");
	ds_list_add(bla, "B is not 1987");
	ds_list_add(bla, "Alfred is not B");
	ds_list_add(bla, "Bruce is not B");
	ds_list_add(bla, "B is not Eduardo");
	ds_list_add(bla, "Virgil is not B");
	ds_list_add(bla, "1983 is not C");
	ds_list_add(bla, "C is not 1984");
	ds_list_add(bla, "C is not 1986");
	ds_list_add(bla, "1987 is not C");
	ds_list_add(bla, "C is not Alfred");
	ds_list_add(bla, "C is not Bruce");
	ds_list_add(bla, "Horace is not C");
	ds_list_add(bla, "C is not Virgil");
	ds_list_add(bla, "1983 is not D");
	ds_list_add(bla, "D is not 1984");
	ds_list_add(bla, "D is not 1985");
	ds_list_add(bla, "1987 is not D");
	ds_list_add(bla, "Alfred is not D");
	ds_list_add(bla, "Eduardo is not D");
	ds_list_add(bla, "D is not Horace");
	ds_list_add(bla, "D is not Virgil");
	ds_list_add(bla, "E is not 1983");
	ds_list_add(bla, "E is not 1984");
	ds_list_add(bla, "1985 is not E");
	ds_list_add(bla, "1986 is not E");
	ds_list_add(bla, "Bruce is not E");
	ds_list_add(bla, "Eduardo is not E");
	ds_list_add(bla, "Horace is not E");
	ds_list_add(bla, "Virgil is not E");
	ds_list_add(bla, "Alfred is not 1983");
	ds_list_add(bla, "Bruce is not 1983");
	ds_list_add(bla, "Eduardo is not 1983");
	ds_list_add(bla, "1983 is not Horace");
	ds_list_add(bla, "Alfred is not 1984");
	ds_list_add(bla, "Bruce is not 1984");
	ds_list_add(bla, "1984 is not Eduardo");
	ds_list_add(bla, "Virgil is not 1984");
	ds_list_add(bla, "Alfred is not 1985");
	ds_list_add(bla, "Bruce is not 1985");
	ds_list_add(bla, "1985 is not Horace");
	ds_list_add(bla, "Virgil is not 1985");
	ds_list_add(bla, "1986 is not Alfred");
	ds_list_add(bla, "Eduardo is not 1986");
	ds_list_add(bla, "Horace is not 1986");
	ds_list_add(bla, "Virgil is not 1986");
	ds_list_add(bla, "Bruce is not 1987");
	ds_list_add(bla, "Eduardo is not 1987");
	ds_list_add(bla, "1987 is not Horace");
	ds_list_add(bla, "Virgil is not 1987");
	ds_list_add(bla, "A either 1983 or 1984");
	ds_list_add(bla, "A either 1983 or 1985");
	ds_list_add(bla, "A either 1986 or 1983");
	ds_list_add(bla, "A either 1983 or 1987");
	ds_list_add(bla, "A either 1983 or Alfred");
	ds_list_add(bla, "1983 either A or Bruce");
	ds_list_add(bla, "1983 either Eduardo or A");
	ds_list_add(bla, "1983 either Horace or A");
	ds_list_add(bla, "Virgil either 1984 or A");
	ds_list_add(bla, "A either Virgil or 1985");
	ds_list_add(bla, "A either 1986 or Virgil");
	ds_list_add(bla, "A either Virgil or 1987");
	ds_list_add(bla, "A either Alfred or Virgil");
	ds_list_add(bla, "A either Bruce or Virgil");
	ds_list_add(bla, "A either Eduardo or Virgil");
	ds_list_add(bla, "A either Horace or Virgil");
	ds_list_add(bla, "B either 1983 or 1984");
	ds_list_add(bla, "B either 1984 or 1985");
	ds_list_add(bla, "B either 1986 or 1984");
	ds_list_add(bla, "B either 1987 or 1984");
	ds_list_add(bla, "1984 either Alfred or B");
	ds_list_add(bla, "B either Bruce or 1984");
	ds_list_add(bla, "B either 1984 or Eduardo");
	ds_list_add(bla, "B either Virgil or 1984");
	ds_list_add(bla, "B either 1983 or Horace");
	ds_list_add(bla, "Horace either B or 1985");
	ds_list_add(bla, "B either Horace or 1986");
	ds_list_add(bla, "B either Horace or 1987");
	ds_list_add(bla, "B either Alfred or Horace");
	ds_list_add(bla, "B either Bruce or Horace");
	ds_list_add(bla, "B either Eduardo or Horace");
	ds_list_add(bla, "B either Virgil or Horace");
	ds_list_add(bla, "C either 1984 or 1985");
	ds_list_add(bla, "C either 1986 or 1985");
	ds_list_add(bla, "C either 1987 or 1985");
	ds_list_add(bla, "1985 either Alfred or C");
	ds_list_add(bla, "1985 either Bruce or C");
	ds_list_add(bla, "1985 either Horace or C");
	ds_list_add(bla, "C either 1985 or Virgil");
	ds_list_add(bla, "C either Eduardo or 1983");
	ds_list_add(bla, "C either Eduardo or 1984");
	ds_list_add(bla, "Eduardo either 1986 or C");
	ds_list_add(bla, "C either Eduardo or 1987");
	ds_list_add(bla, "C either Alfred or Eduardo");
	ds_list_add(bla, "C either Bruce or Eduardo");
	ds_list_add(bla, "C either Eduardo or Horace");
	ds_list_add(bla, "C either Virgil or Eduardo");
	ds_list_add(bla, "D either 1986 or 1983");
	ds_list_add(bla, "D either 1984 or 1986");
	ds_list_add(bla, "D either 1985 or 1986");
	ds_list_add(bla, "D either 1987 or 1986");
	ds_list_add(bla, "1986 either D or Alfred");
	ds_list_add(bla, "D either 1986 or Eduardo");
	ds_list_add(bla, "1986 either D or Horace");
	ds_list_add(bla, "1986 either Virgil or D");
	ds_list_add(bla, "Bruce either D or 1983");
	ds_list_add(bla, "D either 1984 or Bruce");
	ds_list_add(bla, "D either Bruce or 1985");
	ds_list_add(bla, "Bruce either D or 1987");
	ds_list_add(bla, "D either Alfred or Bruce");
	ds_list_add(bla, "D either Bruce or Eduardo");
	ds_list_add(bla, "D either Horace or Bruce");
	ds_list_add(bla, "D either Bruce or Virgil");
	ds_list_add(bla, "E either 1983 or 1987");
	ds_list_add(bla, "E either 1987 or 1984");
	ds_list_add(bla, "E either 1985 or 1987");
	ds_list_add(bla, "E either 1987 or 1986");
	ds_list_add(bla, "E either 1987 or Bruce");
	ds_list_add(bla, "E either Eduardo or 1987");
	ds_list_add(bla, "E either 1987 or Horace");
	ds_list_add(bla, "E either Virgil or 1987");
	ds_list_add(bla, "E either 1983 or Alfred");
	ds_list_add(bla, "E either Alfred or 1984");
	ds_list_add(bla, "E either 1985 or Alfred");
	ds_list_add(bla, "Alfred either E or 1986");
	ds_list_add(bla, "E either Alfred or Bruce");
	ds_list_add(bla, "E either Eduardo or Alfred");
	ds_list_add(bla, "E either Horace or Alfred");
	ds_list_add(bla, "E either Virgil or Alfred");
	ds_list_add(bla, "1983 either B or A");
	ds_list_add(bla, "1983 either C or A");
	ds_list_add(bla, "1983 either D or A");
	ds_list_add(bla, "1983 either E or A");
	ds_list_add(bla, "1983 either B or Virgil");
	ds_list_add(bla, "Virgil either C or 1983");
	ds_list_add(bla, "1983 either Virgil or D");
	ds_list_add(bla, "1983 either Virgil or E");
	ds_list_add(bla, "1983 either Virgil or Alfred");
	ds_list_add(bla, "1983 either Virgil or Bruce");
	ds_list_add(bla, "1983 either Eduardo or Virgil");
	ds_list_add(bla, "1983 either Virgil or Horace");
	ds_list_add(bla, "1984 either B or A");
	ds_list_add(bla, "1984 either C or B");
	ds_list_add(bla, "1984 either B or D");
	ds_list_add(bla, "1984 either B or E");
	ds_list_add(bla, "Horace either A or 1984");
	ds_list_add(bla, "1984 either Horace or C");
	ds_list_add(bla, "Horace either D or 1984");
	ds_list_add(bla, "1984 either Horace or E");
	ds_list_add(bla, "1984 either Alfred or Horace");
	ds_list_add(bla, "1984 either Horace or Bruce");
	ds_list_add(bla, "1984 either Horace or Eduardo");
	ds_list_add(bla, "1984 either Horace or Virgil");
	ds_list_add(bla, "1985 either C or A");
	ds_list_add(bla, "1985 either C or B");
	ds_list_add(bla, "1985 either C or D");
	ds_list_add(bla, "1985 either C or E");
	ds_list_add(bla, "1985 either Eduardo or A");
	ds_list_add(bla, "1985 either Eduardo or B");
	ds_list_add(bla, "Eduardo either D or 1985");
	ds_list_add(bla, "1985 either Eduardo or E");
	ds_list_add(bla, "1985 either Alfred or Eduardo");
	ds_list_add(bla, "1985 either Eduardo or Bruce");
	ds_list_add(bla, "1985 either Horace or Eduardo");
	ds_list_add(bla, "1985 either Eduardo or Virgil");
	ds_list_add(bla, "1986 either D or A");
	ds_list_add(bla, "1986 either B or D");
	ds_list_add(bla, "1986 either C or D");
	ds_list_add(bla, "1986 either E or D");
	ds_list_add(bla, "1986 either A or Bruce");
	ds_list_add(bla, "1986 either B or Bruce");
	ds_list_add(bla, "Bruce either 1986 or C");
	ds_list_add(bla, "Bruce either E or 1986");
	ds_list_add(bla, "1986 either Alfred or Bruce");
	ds_list_add(bla, "1986 either Eduardo or Bruce");
	ds_list_add(bla, "1986 either Bruce or Horace");
	ds_list_add(bla, "1986 either Virgil or Bruce");
	ds_list_add(bla, "1987 either E or A");
	ds_list_add(bla, "1987 either E or B");
	ds_list_add(bla, "1987 either E or C");
	ds_list_add(bla, "1987 either D or E");
	ds_list_add(bla, "1987 either Alfred or A");
	ds_list_add(bla, "1987 either B or Alfred");
	ds_list_add(bla, "Alfred either 1987 or C");
	ds_list_add(bla, "1987 either D or Alfred");
	ds_list_add(bla, "1987 either Bruce or Alfred");
	ds_list_add(bla, "1987 either Eduardo or Alfred");
	ds_list_add(bla, "1987 either Horace or Alfred");
	ds_list_add(bla, "1987 either Virgil or Alfred");
	ds_list_add(bla, "Alfred either E or A");
	ds_list_add(bla, "Alfred either E or B");
	ds_list_add(bla, "Alfred either C or E");
	ds_list_add(bla, "Alfred either E or D");
	ds_list_add(bla, "Alfred either 1983 or 1987");
	ds_list_add(bla, "Alfred either 1987 or 1984");
	ds_list_add(bla, "Alfred either 1987 or 1985");
	ds_list_add(bla, "Alfred either 1986 or 1987");
	ds_list_add(bla, "Bruce either D or Aa")
	ds_list_add(bla, "Bruce either B or D");
	ds_list_add(bla, "Bruce either D or C");
	ds_list_add(bla, "Bruce either D or E");
	ds_list_add(bla, "Bruce either 1986 or 1983");
	ds_list_add(bla, "Bruce either 1986 or 1984");
	ds_list_add(bla, "Bruce either 1985 or 1986");
	ds_list_add(bla, "Bruce either 1987 or 1986");
	ds_list_add(bla, "Eduardo either C or A");
	ds_list_add(bla, "Eduardo either C or B");
	ds_list_add(bla, "Eduardo either C or D");
	ds_list_add(bla, "Eduardo either E or C");
	ds_list_add(bla, "Eduardo either 1985 or 1983");
	ds_list_add(bla, "Eduardo either 1985 or 1984");
	ds_list_add(bla, "Eduardo either 1985 or 1986");
	ds_list_add(bla, "Eduardo either 1985 or 1987");
	ds_list_add(bla, "Horace either A or B");
	ds_list_add(bla, "Horace either B or C");
	ds_list_add(bla, "Horace either D or B");
	ds_list_add(bla, "Horace either B or E");
	ds_list_add(bla, "Horace either 1983 or 1984");
	ds_list_add(bla, "Horace either 1985 or 1984");
	ds_list_add(bla, "Horace either 1984 or 1986");
	ds_list_add(bla, "Horace either 1984 or 1987");
	ds_list_add(bla, "Virgil either A or B");
	ds_list_add(bla, "Virgil either A or C");
	ds_list_add(bla, "Virgil either D or A");
	ds_list_add(bla, "Virgil either A or E");
	ds_list_add(bla, "Virgil either 1983 or 1984");
	ds_list_add(bla, "Virgil either 1983 or 1985");
	ds_list_add(bla, "Virgil either 1983 or 1986");
	ds_list_add(bla, "Virgil either 1987 or 1983");
	ds_list_add(bla, "A neither 1985 nor 1984");
	ds_list_add(bla, "A neither 1986 nor 1984");
	ds_list_add(bla, "A neither 1987 nor 1984");
	ds_list_add(bla, "1984 neither Alfred nor A");
	ds_list_add(bla, "Bruce neither A nor 1984");
	ds_list_add(bla, "Eduardo neither 1984 nor A");
	ds_list_add(bla, "A neither 1985 nor 1986");
	ds_list_add(bla, "A neither 1985 nor 1987");
	ds_list_add(bla, "Alfred neither 1985 nor A");
	ds_list_add(bla, "Bruce neither 1985 nor A");
	ds_list_add(bla, "Horace neither 1985 nor A");
	ds_list_add(bla, "A neither 1987 nor 1986");
	ds_list_add(bla, "Alfred neither A nor 1986");
	ds_list_add(bla, "Eduardo neither 1986 nor A");
	ds_list_add(bla, "Horace neither 1986 nor A");
	ds_list_add(bla, "Bruce neither 1987 nor A");
	ds_list_add(bla, "Eduardo neither 1987 nor A");
	ds_list_add(bla, "Horace neither 1987 nor A");
	ds_list_add(bla, "A neither Alfred nor Bruce");
	ds_list_add(bla, "A neither Alfred nor Eduardo");
	ds_list_add(bla, "A neither Alfred nor Horace");
	ds_list_add(bla, "A neither Bruce nor Eduardo");
	ds_list_add(bla, "A neither Horace nor Bruce");
	ds_list_add(bla, "A neither Eduardo nor Horace");
	ds_list_add(bla, "B neither 1983 nor 1985");
	ds_list_add(bla, "B neither 1983 nor 1986");
	ds_list_add(bla, "B neither 1983 nor 1987");
	ds_list_add(bla, "Alfred neither B nor 1983");
	ds_list_add(bla, "B neither Bruce nor 1983");
	ds_list_add(bla, "Eduardo neither 1983 nor B");
	ds_list_add(bla, "B neither 1986 nor 1985");
	ds_list_add(bla, "B neither 1985 nor 1987");
	ds_list_add(bla, "Alfred neither 1985 nor B");
	ds_list_add(bla, "Bruce neither B nor 1985");
	ds_list_add(bla, "Virgil neither 1985 nor B");
	ds_list_add(bla, "B neither 1986 nor 1987");
	ds_list_add(bla, "Alfred neither 1986 nor B");
	ds_list_add(bla, "Eduardo neither 1986 nor B");
	ds_list_add(bla, "Virgil neither B nor 1986");
	ds_list_add(bla, "1987 neither Bruce nor B");
	ds_list_add(bla, "Eduardo neither 1987 nor B");
	ds_list_add(bla, "Virgil neither 1987 nor B");
	ds_list_add(bla, "B neither Bruce nor Alfred");
	ds_list_add(bla, "B neither Alfred nor Eduardo");
	ds_list_add(bla, "B neither Alfred nor Virgil");
	ds_list_add(bla, "B neither Bruce nor Eduardo");
	ds_list_add(bla, "B neither Bruce nor Virgil");
	ds_list_add(bla, "B neither Eduardo nor Virgil");
	ds_list_add(bla, "C neither 1984 nor 1983");
	ds_list_add(bla, "C neither 1983 nor 1986");
	ds_list_add(bla, "C neither 1987 nor 1983");
	ds_list_add(bla, "1983 neither Alfred nor C");
	ds_list_add(bla, "Bruce neither 1983 nor C");
	ds_list_add(bla, "Horace neither 1983 nor C");
	ds_list_add(bla, "C neither 1986 nor 1984");
	ds_list_add(bla, "C neither 1987 nor 1984");
	ds_list_add(bla, "Alfred neither C nor 1984");
	ds_list_add(bla, "Bruce neither C nor 1984");
	ds_list_add(bla, "Virgil neither C nor 1984");
	ds_list_add(bla, "C neither 1986 nor 1987");
	ds_list_add(bla, "Alfred neither C nor 1986");
	ds_list_add(bla, "C neither Horace nor 1986");
	ds_list_add(bla, "Virgil neither 1986 nor C");
	ds_list_add(bla, "1987 neither Bruce nor C");
	ds_list_add(bla, "Horace neither C nor 1987");
	ds_list_add(bla, "1987 neither C nor Virgil");
	ds_list_add(bla, "C neither Alfred nor Bruce");
	ds_list_add(bla, "C neither Alfred nor Horace");
	ds_list_add(bla, "C neither Alfred nor Virgil");
	ds_list_add(bla, "C neither Horace nor Bruce");
	ds_list_add(bla, "C neither Bruce nor Virgil");
	ds_list_add(bla, "C neither Virgil nor Horace");
	ds_list_add(bla, "D neither 1983 nor 1984");
	ds_list_add(bla, "D neither 1983 nor 1985");
	ds_list_add(bla, "D neither 1987 nor 1983");
	ds_list_add(bla, "Alfred neither 1983 nor D");
	ds_list_add(bla, "Eduardo neither 1983 nor D");
	ds_list_add(bla, "Horace neither D nor 1983");
	ds_list_add(bla, "D neither 1984 nor 1985");
	ds_list_add(bla, "D neither 1984 nor 1987");
	ds_list_add(bla, "Alfred neither 1984 nor D");
	ds_list_add(bla, "Eduardo neither D nor 1984");
	ds_list_add(bla, "1984 neither Virgil nor D");
	ds_list_add(bla, "D neither 1985 nor 1987");
	ds_list_add(bla, "Alfred neither D nor 1985");
	ds_list_add(bla, "Horace neither 1985 nor D");
	ds_list_add(bla, "Virgil neither 1985 nor D");
	ds_list_add(bla, "Eduardo neither 1987 nor D");
	ds_list_add(bla, "Horace neither D nor 1987");
	ds_list_add(bla, "Virgil neither 1987 nor D");
	ds_list_add(bla, "D neither Eduardo nor Alfred");
	ds_list_add(bla, "D neither Alfred nor Horace");
	ds_list_add(bla, "D neither Virgil nor Alfred");
	ds_list_add(bla, "D neither Eduardo nor Horace");
	ds_list_add(bla, "D neither Virgil nor Eduardo");
	ds_list_add(bla, "D neither Horace nor Virgil");
	ds_list_add(bla, "E neither 1983 nor 1984");
	ds_list_add(bla, "E neither 1983 nor 1985");
	ds_list_add(bla, "E neither 1986 nor 1983");
	ds_list_add(bla, "Bruce neither E nor 1983");
	ds_list_add(bla, "Eduardo neither E nor 1983");
	ds_list_add(bla, "Horace neither E nor 1983");
	ds_list_add(bla, "E neither 1985 nor 1984");
	ds_list_add(bla, "E neither 1986 nor 1984");
	ds_list_add(bla, "1984 neither E nor Bruce");
	ds_list_add(bla, "Eduardo neither E nor 1984");
	ds_list_add(bla, "Virgil neither 1984 nor E");
	ds_list_add(bla, "E neither 1985 nor 1986");
	ds_list_add(bla, "Bruce neither 1985 nor E");
	ds_list_add(bla, "Horace neither E nor 1985");
	ds_list_add(bla, "1985 neither E nor Virgil");
	ds_list_add(bla, "Eduardo neither E nor 1986");
	ds_list_add(bla, "Horace neither E nor 1986");
	ds_list_add(bla, "1986 neither Virgil nor E");
	ds_list_add(bla, "E neither Bruce nor Eduardo");
	ds_list_add(bla, "E neither Horace nor Bruce");
	ds_list_add(bla, "E neither Bruce nor Virgil");
	ds_list_add(bla, "E neither Eduardo nor Horace");
	ds_list_add(bla, "E neither Virgil nor Eduardo");
	ds_list_add(bla, "E neither Horace nor Virgil");
	ds_list_add(bla, "1983 neither B nor C");
	ds_list_add(bla, "1983 neither D nor B");
	ds_list_add(bla, "1983 neither B nor E");
	ds_list_add(bla, "1983 neither D nor C");
	ds_list_add(bla, "1983 neither C nor E");
	ds_list_add(bla, "1983 neither E nor D");
	ds_list_add(bla, "1983 neither Alfred nor Bruce");
	ds_list_add(bla, "1983 neither Eduardo nor Alfred");
	ds_list_add(bla, "1983 neither Alfred nor Horace");
	ds_list_add(bla, "1983 neither Eduardo nor Bruce");
	ds_list_add(bla, "1983 neither Bruce nor Horace");
	ds_list_add(bla, "1983 neither Horace nor Eduardo");
	ds_list_add(bla, "1984 neither C nor A");
	ds_list_add(bla, "1984 neither D nor A");
	ds_list_add(bla, "1984 neither E nor A");
	ds_list_add(bla, "1984 neither C nor D");
	ds_list_add(bla, "1984 neither C nor E");
	ds_list_add(bla, "1984 neither E nor D");
	ds_list_add(bla, "1984 neither Alfred nor Bruce");
	ds_list_add(bla, "1984 neither Alfred nor Eduardo");
	ds_list_add(bla, "1984 neither Alfred nor Virgil");
	ds_list_add(bla, "1984 neither Eduardo nor Bruce");
	ds_list_add(bla, "1984 neither Bruce nor Virgil");
	ds_list_add(bla, "1984 neither Virgil nor Eduardo");
	ds_list_add(bla, "1985 neither B nor A");
	ds_list_add(bla, "1985 neither D nor A");
	ds_list_add(bla, "1985 neither A nor E");
	ds_list_add(bla, "1985 neither B nor D");
	ds_list_add(bla, "1985 neither E nor B");
	ds_list_add(bla, "1985 neither D nor E");
	ds_list_add(bla, "1985 neither Alfred nor Bruce");
	ds_list_add(bla, "1985 neither Horace nor Alfred");
	ds_list_add(bla, "1985 neither Virgil nor Alfred");
	ds_list_add(bla, "1985 neither Bruce nor Horace");
	ds_list_add(bla, "1985 neither Bruce nor Virgil");
	ds_list_add(bla, "1985 neither Horace nor Virgil");
	ds_list_add(bla, "1986 neither A nor B");
	ds_list_add(bla, "1986 neither A nor C");
	ds_list_add(bla, "1986 neither E nor A");
	ds_list_add(bla, "1986 neither B nor C");
	ds_list_add(bla, "1986 neither E nor B");
	ds_list_add(bla, "1986 neither E nor C");
	ds_list_add(bla, "1986 neither Eduardo nor Alfred");
	ds_list_add(bla, "1986 neither Alfred nor Horace");
	ds_list_add(bla, "1986 neither Virgil nor Alfred");
	ds_list_add(bla, "1986 neither Eduardo nor Horace");
	ds_list_add(bla, "1986 neither Virgil nor Eduardo");
	ds_list_add(bla, "1986 neither Horace nor Virgil");
	ds_list_add(bla, "1987 neither A nor B");
	ds_list_add(bla, "1987 neither A nor C");
	ds_list_add(bla, "1987 neither D nor A");
	ds_list_add(bla, "1987 neither C nor B");
	ds_list_add(bla, "1987 neither D nor B");
	ds_list_add(bla, "1987 neither C nor D");
	ds_list_add(bla, "1987 neither Bruce nor Eduardo");
	ds_list_add(bla, "1987 neither Bruce nor Horace");
	ds_list_add(bla, "1987 neither Bruce nor Virgil");
	ds_list_add(bla, "1987 neither Eduardo nor Horace");
	ds_list_add(bla, "1987 neither Virgil nor Eduardo");
	ds_list_add(bla, "1987 neither Virgil nor Horace");
	ds_list_add(bla, "Alfred neither A nor B");
	ds_list_add(bla, "Alfred neither C nor A");
	ds_list_add(bla, "Alfred neither A nor D");
	ds_list_add(bla, "Alfred neither B nor C");
	ds_list_add(bla, "Alfred neither B nor D");
	ds_list_add(bla, "Alfred neither C nor D");
	ds_list_add(bla, "Alfred neither 1984 nor 1983");
	ds_list_add(bla, "Alfred neither 1983 nor 1985");
	ds_list_add(bla, "Alfred neither 1986 nor 1983");
	ds_list_add(bla, "Alfred neither 1985 nor 1984");
	ds_list_add(bla, "Alfred neither 1984 nor 1986");
	ds_list_add(bla, "Alfred neither 1986 nor 1985");
	ds_list_add(bla, "Bruce neither B nor A");
	ds_list_add(bla, "Bruce neither C nor A");
	ds_list_add(bla, "Bruce neither A nor E");
	ds_list_add(bla, "Bruce neither B nor C");
	ds_list_add(bla, "Bruce neither B nor E");
	ds_list_add(bla, "Bruce neither C nor E");
	ds_list_add(bla, "Bruce neither 1983 nor 1984");
	ds_list_add(bla, "Bruce neither 1985 nor 1983");
	ds_list_add(bla, "Bruce neither 1987 nor 1983");
	ds_list_add(bla, "Bruce neither 1985 nor 1984");
	ds_list_add(bla, "Bruce neither 1987 nor 1984");
	ds_list_add(bla, "Bruce neither 1987 nor 1985");
	ds_list_add(bla, "Eduardo neither B nor A");
	ds_list_add(bla, "Eduardo neither A nor D");
	ds_list_add(bla, "Eduardo neither E nor A");
	ds_list_add(bla, "Eduardo neither D nor B");
	ds_list_add(bla, "Eduardo neither B nor E");
	ds_list_add(bla, "Eduardo neither E nor D");
	ds_list_add(bla, "Eduardo neither 1983 nor 1984");
	ds_list_add(bla, "Eduardo neither 1986 nor 1983");
	ds_list_add(bla, "Eduardo neither 1987 nor 1983");
	ds_list_add(bla, "Eduardo neither 1986 nor 1984");
	ds_list_add(bla, "Eduardo neither 1987 nor 1984");
	ds_list_add(bla, "Eduardo neither 1986 nor 1987");
	ds_list_add(bla, "Horace neither A nor C");
	ds_list_add(bla, "Horace neither A nor D");
	ds_list_add(bla, "Horace neither E nor A");
	ds_list_add(bla, "Horace neither D nor C");
	ds_list_add(bla, "Horace neither E nor C");
	ds_list_add(bla, "Horace neither D nor E");
	ds_list_add(bla, "Horace neither 1983 nor 1985");
	ds_list_add(bla, "Horace neither 1986 nor 1983");
	ds_list_add(bla, "Horace neither 1987 nor 1983");
	ds_list_add(bla, "Horace neither 1985 nor 1986");
	ds_list_add(bla, "Horace neither 1985 nor 1987");
	ds_list_add(bla, "Horace neither 1986 nor 1987");
	ds_list_add(bla, "Virgil neither C nor B");
	ds_list_add(bla, "Virgil neither D nor B");
	ds_list_add(bla, "Virgil neither B nor E");
	ds_list_add(bla, "Virgil neither C nor D");
	ds_list_add(bla, "Virgil neither E nor C");
	ds_list_add(bla, "Virgil neither D nor E");
	ds_list_add(bla, "Virgil neither 1985 nor 1984");
	ds_list_add(bla, "Virgil neither 1986 nor 1984");
	ds_list_add(bla, "Virgil neither 1987 nor 1984");
	ds_list_add(bla, "Virgil neither 1986 nor 1985");
	ds_list_add(bla, "Virgil neither 1987 nor 1985");
	ds_list_add(bla, "Virgil neither 1986 nor 1987");
	ds_list_add(bla, "five are Alfred 1986 C A B");
	ds_list_add(bla, "five are 1987 A B C Bruce");
	ds_list_add(bla, "five are B Alfred D A 1985");
	ds_list_add(bla, "five are B D Eduardo A 1987");
	ds_list_add(bla, "five are E B 1985 A Bruce");
	ds_list_add(bla, "five are 1986 E A B Eduardo");
	ds_list_add(bla, "five are 1986 1985 Alfred B A");
	ds_list_add(bla, "five are Bruce 1987 B 1985 A");
	ds_list_add(bla, "five are Bruce A B 1985 Alfred");
	ds_list_add(bla, "five are B Eduardo 1986 A 1987");
	ds_list_add(bla, "five are A Alfred Eduardo 1986 B");
	ds_list_add(bla, "five are Bruce Eduardo B A 1987");
	ds_list_add(bla, "five are A D Alfred C 1984");
	ds_list_add(bla, "five are Horace A C D 1987");
	ds_list_add(bla, "five are Bruce E C A 1984");
	ds_list_add(bla, "five are A E 1986 Horace C");
	ds_list_add(bla, "five are C Alfred 1986 1984 A");
	ds_list_add(bla, "five are Bruce C 1984 1987 A");
	ds_list_add(bla, "five are Alfred Bruce C 1984 A");
	ds_list_add(bla, "five are 1987 C A 1986 Horace");
	ds_list_add(bla, "five are Alfred 1986 C Horace A");
	ds_list_add(bla, "five are Bruce A Horace C 1987");
	ds_list_add(bla, "five are 1984 Eduardo D E A");
	ds_list_add(bla, "five are D Horace A 1985 E");
	ds_list_add(bla, "five are D 1984 1985 A Alfred");
	ds_list_add(bla, "five are A 1984 1987 Eduardo D");
	ds_list_add(bla, "five are 1984 Alfred A Eduardo D");
	ds_list_add(bla, "five are D 1985 1987 Horace A");
	ds_list_add(bla, "five are Alfred Horace D A 1985");
	ds_list_add(bla, "five are D 1987 A Eduardo Horace");
	ds_list_add(bla, "five are 1985 1984 E A Bruce");
	ds_list_add(bla, "five are 1984 E 1986 A Eduardo");
	ds_list_add(bla, "five are A Eduardo Bruce E 1984");
	ds_list_add(bla, "five are 1986 1985 E A Horace");
	ds_list_add(bla, "five are 1985 E Bruce Horace A");
	ds_list_add(bla, "five are A Eduardo 1986 Horace E");
	ds_list_add(bla, "five are 1984 1985 A Alfred 1986");
	ds_list_add(bla, "five are Bruce 1984 1987 1985 A");
	ds_list_add(bla, "five are 1984 Bruce A Alfred 1985");
	ds_list_add(bla, "five are 1986 1987 A 1984 Eduardo");
	ds_list_add(bla, "five are 1986 Alfred Eduardo 1984 A");
	ds_list_add(bla, "five are Bruce A 1987 1984 Eduardo");
	ds_list_add(bla, "five are Eduardo 1984 Alfred Bruce A");
	ds_list_add(bla, "five are A 1985 Horace 1987 1986");
	ds_list_add(bla, "five are Horace 1986 1985 A Alfred");
	ds_list_add(bla, "five are Horace 1985 A Bruce 1987");
	ds_list_add(bla, "five are A 1985 Horace Bruce Alfred");
	ds_list_add(bla, "five are 1986 Eduardo A 1987 Horace");
	ds_list_add(bla, "five are Alfred A Horace 1986 Eduardo");
	ds_list_add(bla, "five are 1987 Eduardo A Horace Bruce");
	ds_list_add(bla, "five are 1983 C B Alfred D");
	ds_list_add(bla, "five are C Virgil 1987 D B");
	ds_list_add(bla, "five are 1983 B Bruce C E");
	ds_list_add(bla, "five are Virgil 1986 B E C");
	ds_list_add(bla, "five are B C Alfred 1983 1986");
	ds_list_add(bla, "five are Bruce 1987 B 1983 C");
	ds_list_add(bla, "five are B Alfred Bruce 1983 C");
	ds_list_add(bla, "five are B C 1986 1987 Virgil");
	ds_list_add(bla, "five are Alfred C 1986 Virgil B");
	ds_list_add(bla, "five are 1987 B Bruce C Virgil");
	ds_list_add(bla, "five are E 1983 B Eduardo D");
	ds_list_add(bla, "five are E Virgil D 1985 B");
	ds_list_add(bla, "five are D 1985 Alfred B 1983");
	ds_list_add(bla, "five are 1983 B Eduardo D 1987");
	ds_list_add(bla, "five are D Alfred Eduardo B 1983");
	ds_list_add(bla, "five are 1987 D Virgil B 1985");
	ds_list_add(bla, "five are Alfred Virgil D B 1985");
	ds_list_add(bla, "five are D Eduardo B 1987 Virgil");
	ds_list_add(bla, "five are B Bruce 1983 E 1985");
	ds_list_add(bla, "five are 1983 1986 B Eduardo E");
	ds_list_add(bla, "five are 1983 E B Bruce Eduardo");
	ds_list_add(bla, "five are 1986 1985 B E Virgil");
	ds_list_add(bla, "five are Virgil E B 1985 Bruce");
	ds_list_add(bla, "five are B Virgil Eduardo E 1986");
	ds_list_add(bla, "five are B 1985 1983 1986 Alfred");
	ds_list_add(bla, "five are B Bruce 1983 1987 1985");
	ds_list_add(bla, "five are B 1985 1983 Bruce Alfred");
	ds_list_add(bla, "five are 1986 1983 1987 B Eduardo");
	ds_list_add(bla, "five are 1986 B Eduardo 1983 Alfred");
	ds_list_add(bla, "five are 1987 Eduardo 1983 B Bruce");
	ds_list_add(bla, "five are Alfred Eduardo Bruce B 1983");
	ds_list_add(bla, "five are 1986 Virgil 1987 B 1985");
	ds_list_add(bla, "five are 1986 1985 Virgil B Alfred");
	ds_list_add(bla, "five are 1987 B Virgil Bruce 1985");
	ds_list_add(bla, "five are Alfred Virgil B Bruce 1985");
	ds_list_add(bla, "five are 1987 1986 B Eduardo Virgil");
	ds_list_add(bla, "five are Eduardo B Alfred Virgil 1986");
	ds_list_add(bla, "five are Virgil B 1987 Eduardo Bruce");
	ds_list_add(bla, "five are D Horace E 1983 C");
	ds_list_add(bla, "five are 1984 D E C Virgil");
	ds_list_add(bla, "five are D 1984 C Alfred 1983");
	ds_list_add(bla, "five are C 1987 Horace 1983 D");
	ds_list_add(bla, "five are C Horace D Alfred 1983");
	ds_list_add(bla, "five are D 1984 C Virgil 1987");
	ds_list_add(bla, "five are Virgil Alfred D 1984 C");
	ds_list_add(bla, "five are Horace 1987 Virgil D C");
	ds_list_add(bla, "five are 1983 E 1984 C Bruce");
	ds_list_add(bla, "five are Horace 1986 C 1983 E");
	ds_list_add(bla, "five are 1983 C Bruce E Horace");
	ds_list_add(bla, "five are Virgil 1984 1986 E C");
	ds_list_add(bla, "five are 1984 Virgil C E Bruce");
	ds_list_add(bla, "five are 1986 Virgil Horace C E");
	ds_list_add(bla, "five are 1986 Alfred 1984 C 1983");
	ds_list_add(bla, "five are 1983 Bruce 1984 1987 C");
	ds_list_add(bla, "five are Bruce C Alfred 1984 1983");
	ds_list_add(bla, "five are 1987 1986 Horace 1983 C");
	ds_list_add(bla, "five are 1983 Alfred 1986 Horace C");
	ds_list_add(bla, "five are Bruce 1987 C Horace 1983");
	ds_list_add(bla, "five are Horace Bruce 1983 C Alfred");
	ds_list_add(bla, "five are 1987 Virgil 1984 1986 C");
	ds_list_add(bla, "five are Virgil C Alfred 1986 1984");
	ds_list_add(bla, "five are Bruce C 1984 1987 Virgil");
	ds_list_add(bla, "five are Virgil C Bruce 1984 Alfred");
	ds_list_add(bla, "five are Virgil Horace 1987 1986 C");
	ds_list_add(bla, "five are Virgil 1986 Alfred C Horace");
	ds_list_add(bla, "five are Horace Bruce Virgil 1987 C");
	ds_list_add(bla, "five are D E 1983 1984 Eduardo");
	ds_list_add(bla, "five are Horace D E 1985 1983");
	ds_list_add(bla, "five are D E Eduardo 1983 Horace");
	ds_list_add(bla, "five are E 1984 D Virgil 1985");
	ds_list_add(bla, "five are 1984 D Virgil E Eduardo");
	ds_list_add(bla, "five are Virgil 1985 Horace D E");
	ds_list_add(bla, "five are 1984 1983 Alfred D 1985");
	ds_list_add(bla, "five are D 1983 1987 1984 Eduardo");
	ds_list_add(bla, "five are 1984 Eduardo D 1983 Alfred");
	ds_list_add(bla, "five are Horace 1983 1987 1985 D");
	ds_list_add(bla, "five are 1985 Alfred D 1983 Horace");
	ds_list_add(bla, "five are Eduardo Horace 1987 D 1983");
	ds_list_add(bla, "five are Horace Eduardo D Alfred 1983");
	ds_list_add(bla, "five are Virgil 1987 D 1984 1985");
	ds_list_add(bla, "five are Virgil D Alfred 1984 1985");
	ds_list_add(bla, "five are 1987 D 1984 Virgil Eduardo");
	ds_list_add(bla, "five are D Virgil 1984 Eduardo Alfred");
	ds_list_add(bla, "five are 1987 Horace D Virgil 1985");
	ds_list_add(bla, "five are 1985 Alfred D Virgil Horace");
	ds_list_add(bla, "five are Virgil Eduardo D 1987 Horace");
	ds_list_add(bla, "five are Bruce E 1984 1985 1983");
	ds_list_add(bla, "five are 1986 1984 E 1983 Eduardo");
	ds_list_add(bla, "five are Eduardo 1984 1983 Bruce E");
	ds_list_add(bla, "five are 1986 E 1985 Horace 1983");
	ds_list_add(bla, "five are 1985 Bruce E 1983 Horace");
	ds_list_add(bla, "five are Horace 1986 E 1983 Eduardo");
	ds_list_add(bla, "five are Eduardo Horace 1983 Bruce E");
	ds_list_add(bla, "five are 1985 1984 Virgil E 1986");
	ds_list_add(bla, "five are E Bruce 1985 Virgil 1984");
	ds_list_add(bla, "five are Eduardo Virgil E 1986 1984");
	ds_list_add(bla, "five are E Virgil Eduardo Bruce 1984");
	ds_list_add(bla, "five are Horace 1985 E 1986 Virgil");
	ds_list_add(bla, "five are Bruce Horace 1985 E Virgil");
	ds_list_add(bla, "five are Virgil 1986 Eduardo Horace E");
	ds_list_add(bla, "of 1984 and 1983 , one A and the other B");
	ds_list_add(bla, "of Horace and 1983 , one A and the other B");
	ds_list_add(bla, "of Virgil and 1984 , one B and the other A");
	ds_list_add(bla, "of B and Virgil , one A and the other Horace");
	ds_list_add(bla, "of 1985 and 1983 , one C and the other A");
	ds_list_add(bla, "of A and Eduardo , one 1983 and the other C");
	ds_list_add(bla, "of 1985 and Virgil , one A and the other C");
	ds_list_add(bla, "of Virgil and Eduardo , one C and the other A");
	ds_list_add(bla, "of 1986 and 1983 , one D and the other A");
	ds_list_add(bla, "of Bruce and 1983 , one D and the other A");
	ds_list_add(bla, "of 1986 and Virgil , one A and the other D");
	ds_list_add(bla, "of Bruce and Virgil , one D and the other A");
	ds_list_add(bla, "of 1987 and A , one 1983 and the other E");
	ds_list_add(bla, "of Alfred and A , one E and the other 1983");
	ds_list_add(bla, "of E and Virgil , one 1987 and the other A");
	ds_list_add(bla, "of Alfred and Virgil , one A and the other E");
	ds_list_add(bla, "of 1983 and 1984 , one A and the other Horace");
	ds_list_add(bla, "of Horace and Virgil , one 1984 and the other A");
	ds_list_add(bla, "of 1983 and Eduardo , one A and the other 1985");
	ds_list_add(bla, "of Eduardo and Virgil , one A and the other 1985");
	ds_list_add(bla, "of A and Bruce , one 1983 and the other 1986");
	ds_list_add(bla, "of A and Bruce , one 1986 and the other Virgil");
	ds_list_add(bla, "of Alfred and 1983 , one 1987 and the other A");
	ds_list_add(bla, "of 1987 and Virgil , one A and the other Alfred");
	ds_list_add(bla, "of 1985 and 1984 , one C and the other B");
	ds_list_add(bla, "of Eduardo and 1984 , one B and the other C");
	ds_list_add(bla, "of Horace and 1985 , one C and the other B");
	ds_list_add(bla, "of C and Horace , one B and the other Eduardo");
	ds_list_add(bla, "of 1984 and 1986 , one D and the other B");
	ds_list_add(bla, "of 1984 and Bruce , one D and the other B");
	ds_list_add(bla, "of 1986 and Horace , one B and the other D");
	ds_list_add(bla, "of B and Bruce , one Horace and the other D");
	ds_list_add(bla, "of 1984 and 1987 , one B and the other E");
	ds_list_add(bla, "of B and Alfred , one 1984 and the other E");
	ds_list_add(bla, "of 1987 and Horace , one E and the other B");
	ds_list_add(bla, "of Alfred and Horace , one B and the other E");
	ds_list_add(bla, "of 1984 and Virgil , one B and the other 1983");
	ds_list_add(bla, "of Virgil and Horace , one 1983 and the other B");
	ds_list_add(bla, "of B and Eduardo , one 1985 and the other 1984");
	ds_list_add(bla, "of Horace and 1985 , one Eduardo and the other B");
	ds_list_add(bla, "of 1984 and Bruce , one 1986 and the other B");
	ds_list_add(bla, "of Horace and Bruce , one B and the other 1986");
	ds_list_add(bla, "of 1984 and 1987 , one Alfred and the other B");
	ds_list_add(bla, "of 1987 and Horace , one Alfred and the other B");
	ds_list_add(bla, "of D and 1985 , one C and the other 1986");
	ds_list_add(bla, "of C and D , one Bruce and the other 1985");
	ds_list_add(bla, "of Eduardo and D , one 1986 and the other C");
	ds_list_add(bla, "of Bruce and Eduardo , one D and the other C");
	ds_list_add(bla, "of 1985 and 1987 , one E and the other C");
	ds_list_add(bla, "of Alfred and 1985 , one E and the other C");
	ds_list_add(bla, "of 1987 and Eduardo , one C and the other E");
	ds_list_add(bla, "of Alfred and Eduardo , one E and the other C");
	ds_list_add(bla, "of C and Virgil , one 1983 and the other 1985");
	ds_list_add(bla, "of C and Virgil , one 1983 and the other Eduardo");
	ds_list_add(bla, "of Horace and C , one 1985 and the other 1984");
	ds_list_add(bla, "of Horace and Eduardo , one C and the other 1984");
	ds_list_add(bla, "of C and 1986 , one Bruce and the other 1985");
	ds_list_add(bla, "of 1986 and Eduardo , one Bruce and the other C");
	ds_list_add(bla, "of Alfred and 1985 , one C and the other 1987");
	ds_list_add(bla, "of Eduardo and Alfred , one C and the other 1987");
	ds_list_add(bla, "of 1986 and E , one D and the other 1987");
	ds_list_add(bla, "of D and Alfred , one 1986 and the other E");
	ds_list_add(bla, "of 1987 and Bruce , one E and the other D");
	ds_list_add(bla, "of Bruce and E , one Alfred and the other D");
	ds_list_add(bla, "of D and Virgil , one 1983 and the other 1986");
	ds_list_add(bla, "of Virgil and Bruce , one D and the other 1983");
	ds_list_add(bla, "of 1986 and Horace , one D and the other 1984");
	ds_list_add(bla, "of Horace and D , one 1984 and the other Bruce");
	ds_list_add(bla, "of 1986 and Eduardo , one 1985 and the other D");
	ds_list_add(bla, "of Eduardo and D , one Bruce and the other 1985");
	ds_list_add(bla, "of Alfred and D , one 1987 and the other 1986");
	ds_list_add(bla, "of Alfred and Bruce , one D and the other 1987");
	ds_list_add(bla, "of 1987 and Virgil , one E and the other 1983");
	ds_list_add(bla, "of Virgil and Alfred , one 1983 and the other E");
	ds_list_add(bla, "of Horace and E , one 1987 and the other 1984");
	ds_list_add(bla, "of Alfred and Horace , one E and the other 1984");
	ds_list_add(bla, "of E and Eduardo , one 1985 and the other 1987");
	ds_list_add(bla, "of Eduardo and Alfred , one E and the other 1985");
	ds_list_add(bla, "of Bruce and 1987 , one 1986 and the other E");
	ds_list_add(bla, "of Bruce and E , one 1986 and the other Alfred");
	ds_list_add(bla, "of 1984 and 1983 , one Horace and the other Virgil");
	ds_list_add(bla, "of Virgil and Eduardo , one 1985 and the other 1983");
	ds_list_add(bla, "of Bruce and Virgil , one 1986 and the other 1983");
	ds_list_add(bla, "of Alfred and Virgil , one 1983 and the other 1987");
	ds_list_add(bla, "of Eduardo and Horace , one 1985 and the other 1984");
	ds_list_add(bla, "of Bruce and Horace , one 1984 and the other 1986");
	ds_list_add(bla, "of Alfred and Horace , one 1984 and the other 1987");
	ds_list_add(bla, "of Eduardo and Bruce , one 1985 and the other 1986");
	ds_list_add(bla, "of Eduardo and Alfred , one 1985 and the other 1987");
	ds_list_add(bla, "of Alfred and Bruce , one 1987 and the other 1986");
	ds_list_add(bla, "B 1 Years after A");
	ds_list_add(bla, "Horace 1 Years after A");
	ds_list_add(bla, "B 1 Years after Virgil");
	ds_list_add(bla, "Horace 1 Years after Virgil");
	ds_list_add(bla, "C 2 Years after A");
	ds_list_add(bla, "Eduardo 2 Years after A");
	ds_list_add(bla, "C 2 Years after Virgil");
	ds_list_add(bla, "Eduardo 2 Years after Virgil");
	ds_list_add(bla, "D 3 Years after A");
	ds_list_add(bla, "Bruce 3 Years after A");
	ds_list_add(bla, "D 3 Years after Virgil");
	ds_list_add(bla, "Bruce 3 Years after Virgil");
	ds_list_add(bla, "E 4 Years after A");
	ds_list_add(bla, "Alfred 4 Years after A");
	ds_list_add(bla, "E 4 Years after Virgil");
	ds_list_add(bla, "Alfred 4 Years after Virgil");
	ds_list_add(bla, "A 1 Years before B");
	ds_list_add(bla, "Virgil 1 Years before B");
	ds_list_add(bla, "A 1 Years before Horace");
	ds_list_add(bla, "Virgil 1 Years before Horace");
	ds_list_add(bla, "C 1 Years after B");
	ds_list_add(bla, "Eduardo 1 Years after B");
	ds_list_add(bla, "C 1 Years after Horace");
	ds_list_add(bla, "Eduardo 1 Years after Horace");
	ds_list_add(bla, "D 2 Years after B");
	ds_list_add(bla, "Bruce 2 Years after B");
	ds_list_add(bla, "D 2 Years after Horace");
	ds_list_add(bla, "Bruce 2 Years after Horace");
	ds_list_add(bla, "E 3 Years after B");
	ds_list_add(bla, "Alfred 3 Years after B");
	ds_list_add(bla, "E 3 Years after Horace");
	ds_list_add(bla, "Alfred 3 Years after Horace");
	ds_list_add(bla, "A 2 Years before C");
	ds_list_add(bla, "Virgil 2 Years before C");
	ds_list_add(bla, "A 2 Years before Eduardo");
	ds_list_add(bla, "Virgil 2 Years before Eduardo");
	ds_list_add(bla, "B 1 Years before C");
	ds_list_add(bla, "Horace 1 Years before C");
	ds_list_add(bla, "B 1 Years before Eduardo");
	ds_list_add(bla, "Horace 1 Years before Eduardo");
	ds_list_add(bla, "D 1 Years after C");
	ds_list_add(bla, "Bruce 1 Years after C");
	ds_list_add(bla, "D 1 Years after Eduardo");
	ds_list_add(bla, "Bruce 1 Years after Eduardo");
	ds_list_add(bla, "E 2 Years after C");
	ds_list_add(bla, "Alfred 2 Years after C");
	ds_list_add(bla, "E 2 Years after Eduardo");
	ds_list_add(bla, "Alfred 2 Years after Eduardo");
	ds_list_add(bla, "A 3 Years before D");
	ds_list_add(bla, "Virgil 3 Years before D");
	ds_list_add(bla, "A 3 Years before Bruce");
	ds_list_add(bla, "Virgil 3 Years before Bruce");
	ds_list_add(bla, "B 2 Years before D");
	ds_list_add(bla, "Horace 2 Years before D");
	ds_list_add(bla, "B 2 Years before Bruce");
	ds_list_add(bla, "Horace 2 Years before Bruce");
	ds_list_add(bla, "C 1 Years before D");
	ds_list_add(bla, "Eduardo 1 Years before D");
	ds_list_add(bla, "C 1 Years before Bruce");
	ds_list_add(bla, "Eduardo 1 Years before Bruce");
	ds_list_add(bla, "E 1 Years after D");
	ds_list_add(bla, "Alfred 1 Years after D");
	ds_list_add(bla, "E 1 Years after Bruce");
	ds_list_add(bla, "Alfred 1 Years after Bruce");
	ds_list_add(bla, "A 4 Years before E");
	ds_list_add(bla, "Virgil 4 Years before E");
	ds_list_add(bla, "A 4 Years before Alfred");
	ds_list_add(bla, "Virgil 4 Years before Alfred");
	ds_list_add(bla, "B 3 Years before E");
	ds_list_add(bla, "Horace 3 Years before E");
	ds_list_add(bla, "B 3 Years before Alfred");
	ds_list_add(bla, "Horace 3 Years before Alfred");
	ds_list_add(bla, "C 2 Years before E");
	ds_list_add(bla, "Eduardo 2 Years before E");
	ds_list_add(bla, "C 2 Years before Alfred");
	ds_list_add(bla, "Eduardo 2 Years before Alfred");
	ds_list_add(bla, "D 1 Years before E");
	ds_list_add(bla, "Bruce 1 Years before E");
	ds_list_add(bla, "D 1 Years before Alfred");
	ds_list_add(bla, "Bruce 1 Years before Alfred");


	for(var i = 0; i < ds_list_size(bla); i++){
		//var _string = bla[| i];
		//var _parsed = ParseRuleText(_string)
		//Generate the rule?
		//var _rule = new Rule(_parsed);
		//ds_list_add(obj_Master.rules,_rule);
		//AddRuleSafe(obj_Master.testRules,_rule);
	}

	ds_list_destroy(bla);
}